### ISSUE TITLE
Crashes on reading Newtonsoft.Json

### ISSUE THREAD

**Issue by AlexandreMercierAubin** [borgej/YTBot#2]
System.IO.FileLoadException: 'Could not load file or assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

LOG: Attempting download of new URL file:///A:/.../BeeBot/BeeBot/bin/Newtonsoft.Json.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

Might be my ASP that is outdated, but have you tried running the app on another computer?

**Comment by borgej** [comment]
Hi, sorry havent been working or checking my GitHub repos in a while.
I have redone the whole application now and It should be building on a git clone.
